version: '3'

volumes:
  ipfs:

services:
  db:
    ports:
      - "5432:5432"

  ganache:
    image: trufflesuite/ganache-cli:v6.10.1
    container_name: culturestake-ganache
    ports:
      - "8545:8545"
    command: [
      "--deterministic",
      "--networkId", "5777",
      "--hostname", "0.0.0.0",
      "--accounts", "10",
      "--defaultBalanceEther", "10000",
      "--gasLimit", "10000000",
      "--noVMErrorsOnRPCResponse"
    ]

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    container_name: culturestake-ipfs-node
    ports:
      - "5001:5001"
    volumes:
      - ipfs:/data/ipfs

  graph:
    image: graphprotocol/graph-node:v0.18.0
    container_name: culturestake-graph-node
    depends_on:
      - db
      - ganache
      - ipfs
      - nginx
    ports:
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    environment:
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
      - LETSENCRYPT_HOST=${HOST_GRAPH_NODE}
      - VIRTUAL_HOST=${HOST_GRAPH_NODE}
      - VIRTUAL_PORT=8000
      - ethereum=${SUBGRAPH_NETWORK}:${ETHEREUM_NODE_ENDPOINT}
      - ipfs=ipfs:5001
      - postgres_db=${POSTGRES_DATABASE_GRAPH_NODE}
      - postgres_host=db:5432
      - postgres_pass=${POSTGRES_PASSWORD}
      - postgres_user=${POSTGRES_USER}
