version: '3'

services:
  db:
    ports:
      - "5432:5432"

  ganache:
    image: trufflesuite/ganache-cli:v6.9.1
    container_name: culturestake-ganache
    ports:
      - "8545:8545"
    command: [
      "--deterministic",
      "--networkId", "5777",
      "--hostname", "0.0.0.0",
      "--accounts", "10",
      "--defaultBalanceEther", "10000",
      "--gasLimit", "10000000",
      "--noVMErrorsOnRPCResponse"
    ]

  graph:
    depends_on:
      - db
      - ganache
      - ipfs
