version: '3'

volumes:
  certs:
  conf:
  data:
  html:
  vhost.d:

services:
  db:
    build: ./db
    container_name: culturestake-db
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  nginx:
    build: ./nginx-proxy
    container_name: culturestake-nginx-proxy
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d

  gen:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile.docker-gen
    container_name: culturestake-nginx-gen
    depends_on:
      - nginx
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup culturestake-nginx-proxy -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
