version: '3'

volumes:
  certs:
  conf:
  data:
  html:
  ipfs:
  vhost.d:

services:
  db:
    image: postgres:12.2-alpine
    container_name: culturestake-db
    env_file:
      - .env
    volumes:
      - ./db/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
      - data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.1-alpine
    container_name: culturestake-redis
    env_file:
      - .env

  nginx:
    image: nginx:1.19.1-alpine
    container_name: culturestake-nginx-proxy
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d

  gen:
    image: jwilder/docker-gen:0.7.0
    container_name: culturestake-nginx-gen
    depends_on:
      - nginx
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    command: -notify-sighup culturestake-nginx-proxy -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        - GIT_COMMIT=c0dfb5b
    container_name: culturestake-api
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - GRAPH_NODE_ENDPOINT=${GRAPH_NODE_ENDPOINT}
      - VIRTUAL_HOST=${HOST_API}
      - LETSENCRYPT_HOST=${HOST_API}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}

