version: '3'

volumes:
  acme:
  uploads:

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"

  letsencrypt:
    image: nginxproxy/acme-companion:2.1.0
    container_name: culturestake-letsencrypt
    restart: always
    depends_on:
      - nginx
      - gen
    environment:
      - NGINX_PROXY_CONTAINER=culturestake-nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=culturestake-nginx-gen
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        - GIT_COMMIT=4ab0795
    container_name: culturestake-app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - GRAPH_NODE_ENDPOINT=${GRAPH_NODE_ENDPOINT}
      - VIRTUAL_HOST=${HOST_APP}
      - LETSENCRYPT_HOST=${HOST_APP}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
    volumes:
      - uploads:/usr/src/app/uploads

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
      args:
        - GIT_COMMIT=4ab0795
    container_name: culturestake-worker
    depends_on: 
      - db
      - redis
    env_file:
      - .env
